### PR TITLE
Replace deprecated Email::Address.

### PR DESCRIPTION
**Pull request by jkeenan**
With recommended Email::Address::XS, as per information at:
http://search.cpan.org/~rjbs/Email-Address-1.909/lib/Email/Address.pm

### CODE REVIEW

**Comment by jkeenan** [comment]
This is probably essentially the same as https://github.com/rjbs/Email-Sender/pull/57/files.  I would like to have the issue addressed so that I can update the [FreeBSD port p5-Email-Sender](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228327).

**Comment by pali** [comment]
In #57 I removed two `grep { defined }` lines as `Email::Address::XS->parse` in array context always returns defined values. Otherwise change is same.

**Comment by jkeenan** [comment]
@rjbs:  Could you please evaluate this p.r.?  It blocks resolution of [a ticket in the FreeBSD bug queue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228327).

Thank you very much.
Jim Keenan

**Comment by dlangille** [comment]
This has become an issue for me with https://www.FreshPorts.org/

If any testing/help is required, I'm happy to do this.

**Comment by pali** [comment]
Perl's Email::* modules are probably unmaintained and dead now as @rjbs does not have time for it.

@dlangille @jkeenan: I asked question is Email::* modules are still live about half a year ago on pep@perl.org mailing list and since then nothing happened... https://www.nntp.perl.org/group/perl.pep/2018/06/msg559.html

**Comment by dlangille** [comment]
Not that I have any great Perl expertise, but in the interests of getting this patched and working, I have forked to https://github.com/dlangille/Email-Sender

pali: I have tried to include your merge request, but failed, and did the update by hand.  I'm testing the amended FreeBSD port now.

**Comment by dlangille** [comment]
re https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=228327

My fork has been updated.

Proposed new patch for mail/p5-Email-Sender now at https://reviews.freebsd.org/D18053

Tested on my development instance of FreshPorts.  More testing requested please.

**Comment by pali** [comment]
@dlangille Would you be interested in becoming new maintainer of this module? :-) I guess that also Linux distributions which have this module packaged can benefit if somebody prepare and maintain new tarballs, etc...

**Comment by dlangille** [comment]
I could, but I would need guidance on how to create the metacpan tarball

**Comment by pali** [comment]
@dlangille you probably do not have cpan account, so would need to register https://pause.perl.org. See also how to adopt existing cpan module http://neilb.org/2013/07/24/adopt-a-module.html. Creating tarball for cpan upload depends on what build system project uses. Email::Sender uses dzill and its documentations is on http://dzil.org/tutorial/release.html (http://dzil.org/tutorial/contents.html). Some other general information/tutorials you can find e.g. on http://tynovsky.github.io/cpan-tutorials/.

**Comment by dlangille** [comment]
@pali Account applied for.

Reading the adoption details, : steps 1-5 of 8 

Thanks

**Comment by dlangille** [comment]
Release with the patch are available at https://github.com/dlangille/Email-Sender/releases

**Comment by karenetheridge** [comment]
As explained in https://www.nntp.perl.org/group/perl.pep/2018/06/msg563.html, this module is not abandoned, and IMO it's rather rude to continue ttempts to take it over or encourage others to take it over.

**Comment by dlangille** [comment]
Thanks Karen.  My work is stopped.

**Comment by rjbs** [comment]
Hi!  This issue is on my radar.  I actually received a patch to sort out some Email::Address issues, and if those work out (very soon, once I'm back from this work trip), I hope to make Email::Sender use XS if available, and otherwise require the un-broken Email::Address.  I agree that, fundamentally, Email::Sender should not depend on and use a module that has broken behavior, of course.  (There are also some questions about the differences in behavior between the XS and pure Perl implementations, but I think we can get away with documenting these, rather than doing any serious work.)

**Comment by dlangille** [comment]
Sounds good to me. Thank you.

**Comment by pali** [comment]
@karenetheridge what is rude on the fact that nothing happened for this module for about one year and there are more people interested in fixing/maintaining? Rude is your argument to stop doing anything and letting this module die!

**Comment by rjbs** [comment]
Done in c5723d4

**Pull request closed without merging**
