### PR TITLE
Changed SSL to use the SSL support in Net::SMTP > 2.37

### PR DESCRIPTION
**Pull request by markwellis**
and added an option to set IO::Socket::SSL options, such as
SSL_verifycn_name

### CODE REVIEW

**Comment by rjbs** [comment]
Net::SMTP v2.37 is part of a libnet later than v1.28, which has a significant bug described in later comments of RT https://rt.cpan.org/Public/Bug/Display.html?id=14875

I'd like to require a version with the fix, which I hope will be out soon.  I will now go back and read the patch assuming that we can rely on that version…

**Comment by rjbs** [comment]
Looks good to me.  I'd like to make sure I can incorporate support for STARTTLS when we merge this, but I'll do that when I do that.  Thanks!  This should be a big improvement, and I appreciate it!

**Comment by karenetheridge** [comment]
It would be very helpful to see this released, even if only as a TRIAL -- we are running into the problem described here after upgrading my libnet distribution to 3.07: http://stackoverflow.com/questions/28709237/installing-netsmtpssl

That is:

```
Caught exception in MyApp::Controller::Blah::User::Email->send_email "Failed to send email: Not a GLOB reference at local-lib/Net/SMTP/SSL.pm line 16.
	require Net/SMTP/SSL.pm called at local-lib/Email/Sender/Transport/SMTP.pm line 100
	Email::Sender::Transport::SMTP::_smtp_client(Email::Sender::Transport::SMTP::Persistent=HASH(0x44fc9528)) called at local-lib/Email/Sender/Transport/SMTP/Persistent.pm line 32
	Email::Sender::Transport::SMTP::Persistent::_smtp_client(Email::Sender::Transport::SMTP::Persistent=HASH(0x44fc9528)) called at local-lib/Email/Sender/Transport/SMTP.pm line 151
	Email::Sender::Transport::SMTP::send_email(Email::Sender::Transport::SMTP::Persistent=HASH(0x44fc9528), Email::Abstract=ARRAY(0x45245330), HASH(0x4525a3d8)) called at local-lib/Email/Sender/Role/CommonSending.pm line 45
	Email::Sender::Role::CommonSending::try {...} () called at local-lib/Try/Tiny.pm line 81
	eval {...} called at local-lib/Try/Tiny.pm line 72
	Try::Tiny::try(CODE(0x45282e90), Try::Tiny::Catch=REF(0x4523a298)) called at local-lib/Email/Sender/Role/CommonSending.pm line 58
	Email::Sender::Role::CommonSending::send(Email::Sender::Transport::SMTP::Persistent=HASH(0x44fc9528), Email::Abstract=ARRAY(0x45245330), HASH(0x4526f008)) called at local-lib/Email/Sender/Simple.pm line 119
	Email::Sender::Simple::send_email("Email::Sender::Simple", Email::Abstract=ARRAY(0x45245330), HASH(0x4523aa48)) called at local-lib/Email/Sender/Role/CommonSending.pm line 45
```

**Comment by karenetheridge** [comment]
Note: I was able to resolve the above stacktrace by updating to the latest Net::SMTP::SSL, which fixes the glob error described at that stackoverflow link.

**Comment by rjbs** [comment]
I believe #39 obsoletes this.  Thank you for your work, on which #39 is built.

**Pull request closed without merging**
